name: ci

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  # FASE 1: Análisis SAST con Bandit (Configuración inicial)
  bandit_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4 # Versión más reciente

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Instalar Bandit
        run: pip install bandit
        
      - name: Ejecutar Bandit Scan
        # -f json: Genera el formato solicitado en el primer punto
        # -o sast-bandit.json: Nombre exacto indicado en el enunciado
        # -ll: Omite severity low (foco en lo importante)
        # -ii: Omite confidence low (evita ruido)
        # || true: Evita que el pipeline se detenga si encuentra vulnerabilidades (para poder subir el artefacto)
        run: bandit -r . -f json -o sast-bandit.json -ll -ii || true
        
      - name: Subir artefacto Bandit
        uses: actions/upload-artifact@v4
        with:
          name: sast-bandit-results
          path: sast-bandit.json

  # FASE 2: Análisis SAST con Semgrep (En paralelo).
  semgrep_scan:
    name: Run Semgrep Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
 
      - name: Ejecutar Semgrep Scan
        # --severity=ERROR  → Crítico/Alto
        # --severity=WARNING → Medio
        # --json: Formato de salida para consumo externo
        # || true: Evita detención del pipeline al encontrar hallazgos
        run: >
          semgrep scan
          --config auto
          --config p/python
          --severity=ERROR
          --severity=WARNING
          --json
          --output=sast-semgrep.json || true
 
      - name: Subir artefacto Semgrep
        uses: actions/upload-artifact@v4
        with:
          name: sast-semgrep-results
          path: sast-semgrep.json


